### ISSUE TITLE
Usage of from_utf8_lossy is misleading

### ISSUE THREAD

**Issue by rohitpaulk** [codecrafters-io/build-your-own-dns-server#16]
In the Rust starter, we're suggesting that the user use from_utf8_lossy on a packet that we know will contain non utf8 characters:

https://github.com/codecrafters-io/build-your-own-dns-server/blob/f24e245fffc37f69d98ad959ec007701227dbe2f/compiled_starters/rust/src/main.rs#L15

Is there another method we can use for the starter here that isn't misleading?

**Comment by pcn** [comment]
I don't recall that `_received_data`  is used, and I think that if the data needs to be visualized, `&[u8]` is actually pretty usefully printable with the debug representation, e.g.:

```rust
println!("Incoming data: {:?}", &buf[0..size]); 
```

Does that work?

**Comment by rohitpaulk** [comment]
I think we can just safely remove the line - @sherubthakur thoughts?

**Comment by sherubthakur** [comment]
@rohitpaulk I plan to remove this line.

@pcn I agree data visualization is useful, however I will let users decide if they want to do it or not. So I will just print some bare minimum. I hope that makes sense.
